### PR TITLE
Sanity check of suggestions ordered by type compatibility

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
@karreiro could we please merge this PR? Not doing cherry pick on background? So I can reference it in jira as additional coverage. Thank you.

**Comment by karreiro** [comment]
@jomarko sure, could you please rollback the change in the `Candidate` class? The rest seems great to me!

**Comment by karreiro** [comment]
(I can cherry-pick the new changes if you prefer to as well)

**Comment by jomarko** [comment]
@karreiro rollback done.

**Comment by karreiro** [comment]
Thank you, @jomarko 🚀

**Pull request merged**
